### ISSUE TITLE
Anchor links

### ISSUE THREAD

**Issue by qbaron** [gwu-libraries/academiccommons-theme#9] opened 2018-08-29 14:12 UTC
This will be vital for the eventual migration of libsite to D8, but is lower priority for AC. We need to be able to add anchor tags from the WYSIWYG editor without have to go into **Source**. The first attempt at fixing this caused an issue where trying to edit an existing link created a double pop-up

**Comment by maxstarkenburg** [comment] 2019-04-30 23:55
Closing this one as a duplicate of gwu-libraries/lai-drupal#15 (it's not really a theme issue, and I can't w/ this ticket title, haha).

**Closed by maxstarkenburg** 2019-04-30 23:55 UTC
