### ISSUE TITLE
Workshops page is displaying non-workshop events

### ISSUE THREAD

**Issue by rdelaloy** [gwu-libraries/academiccommons-theme#2] opened 2018-08-29 13:07 UTC
The Workshops & Events page is displaying an event tagged as "other" in the feed of LAI Workshops. 
![ac workshops page](https://user-images.githubusercontent.com/17850160/44789571-e7e18600-ab6a-11e8-82fe-d110e9b0876c.png)

**Comment by rdelaloy** [comment] 2018-08-29 13:08
FYI - this is also not tagged as "faculty" in our system so I'm changing that now, which may change the way it is displayed on here.

**Comment by maxstarkenburg** [comment] 2019-04-30 23:48
Closing as a duplicate of gwu-libraries/Drupal-Modules#127, which is where the code change (in the "eventsfeed" module) would need to go, though @rdelaloy guidance might be needed in that ticket in terms of whether other event filter categories might need to be reflected in the 6 events showing on that page (e.g. only events open to GWorld cardholders, since that's what the links are going to?).

**Closed by maxstarkenburg** 2019-04-30 23:48 UTC
Labels: bug
